### ISSUE TITLE
Decide on Framework for the Website

### ISSUE THREAD

**Issue by supernoir** [Frontendfu/podcast#4]
The hardest part. Clearly.

**Comment by supernoir** [comment]
Fancy: @Coldwine programmiert etwas glänzendes aus purem Ember.
Lazy: Ich rühr uns schnell ein bisschen Jekyll aus der Packung zusammen.

**Comment by hurrtz** [comment]
Da ich bei dem Meeting gepennt habe und nicht dabei war und das alles nicht mitbekommen habe und so, äh, ist das quasi schon fertig und implizit entschieden (blush)... Ist jetzt ein simpler Wordpress-Blog geworden. Hätte aber eh dafür plädiert, weil es für Wordpress das geniale Podlove gibt, den Podcast-Publisher von Tim Pritlove.

Können wir dann beim nächsten Meeting noch bequatschen.

**Comment by supernoir** [comment]
Aha.... Na dann ;) Gibt's schon was zu sehen?

**Comment by hurrtz** [comment]
frontendfu.de ;)
